---
run:
  skip-dirs:
    - internal/pkg/app/docs

linters-settings:
  misspell:
    locale: US
  errorlint:
    # Report non-wrapping error creation using fmt.Errorf
    errorf: false

linters:
  enable:
    - bodyclose
    - dupl
    - errorlint
    - funlen
    - goconst
    - gosec
    - misspell
    - unconvert
    - prealloc
    - deadcode
  disable:
    - errcheck
    - ineffassign

issues:
  exclude-rules:
    - path: internal/pkg/db/dynamo/fragment_storer\.go
      linters:
        - dupl
    - path: _test\.go
      linters:
        - dupl
        - funlen
        - goconst
    - path: internal/pkg/db/dynamo/tenant_storer\.go
      linters:
        - dupl
    - path: internal/pkg/db/dynamo/dynamodb_storer\.go
      linters:
        - dupl
    - path: internal/pkg/app/handlers_v1\.go
      linters:
        - funlen
        - dupl
    - path: internal/pkg/app/app\.go
      linters:
        - funlen
        - gosec
    - path: pkg/filter/match/patternregex/patternregex\.go
      linters:
        - funlen
    - path: pkg/filter/match/comparison/comparison\.go
      linters:
        - funlen
    - path: pkg/filter/js/goja\.go
      linters:
        - funlen
    - path: pkg/event/event\.go
      linters:
        - funlen
    - path: pkg/filter/hash/hash\.go
      linters:
        - funlen
    - path: pkg/filter/mapping/mapping\.go
      linters:
        - funlen
    - path: pkg/plugin/manager/manager\.go
      linters:
        - funlen
    - path: pkg/plugin/manager\.go
      linters:
        - funlen
    - path: internal/pkg/plugin/manager\.go
      linters:
        - dupl
    - path: pkg/plugins/debug/receiver\.go
      linters:
        - funlen
    - path: pkg/plugins/sqs/receiver\.go
      linters:
        - funlen
    - path: pkg/plugins/kafka/receiver\.go
      linters:
        - funlen
    - path: pkg/plugins/gears/receiver\.go
      linters:
        - funlen
    - path: pkg/plugins/gears/sender\.go
      linters:
        - funlen
    - path: pkg/sharder/distributor\.go
      linters:
        - gosec
    - path: pkg/plugins/kinesis/receiver\.go
      linters:
        - funlen
        - errorlint
        - dupl
    - path: pkg/plugins/s3/receiver\.go
      linters:
        - funlen
    - path: pkg/plugins/s3/sender\.go
      linters:
        - funlen
    - path: pkg/plugins/redis/receiver\.go
      linters:
        - funlen
    - path: pkg/plugins/debug/sender\.go
      linters:
        - funlen
    - path: pkg/plugins/sqs/sender\.go
      linters:
        - funlen
    - path: pkg/plugins/kafka/sender\.go
      linters:
        - funlen
    - path: pkg/plugins/kinesis/sender\.go
      linters:
        - funlen
    - path: pkg/plugins/redis/sender\.go
      linters:
        - funlen
    - path: pkg/plugins/http/sender\.go
      linters:
        - funlen
    - path: pkg/filter/regex/regex\.go
      linters:
        - funlen
    - path: pkg/filter/batch/filter\.go
      linters:
        - funlen
    - path: pkg/ratelimit/adaptive_limiter\.go
      linters:
        - funlen
    - path: internal/pkg/syncer/redis/redis_delta_syncer\.go
      linters:
        - funlen
    - path: pkg/cli/viper\.go
      linters:
        - funlen
    - path: internal/pkg/fx/pluginmanagerfx/module\.go
      linters:
        - funlen
    - path: pkg/filter/decode/decode\.go
      linters:
        - funlen
    - path: internal/pkg/jwt/types\.go
      text: "Potential hardcoded credentials"
      linters:
        - gosec
    - path: pkg/filter/hash/hash\.go
      text: "weak cryptographic primitive"
      linters:
        - gosec
    - path: pkg/hasher/hasher\.go
      text: "weak cryptographic primitive"
      linters:
        - gosec
    - path: pkg/filter/dedup/filter\.go
      text: "weak cryptographic primitive"
      linters:
        - gosec
    - path: pkg/filter/js/goja\.go
      text: "weak cryptographic primitive"
      linters:
        - gosec
    - path: pkg/ratelimit/redis/redis_limiter\.go
      text: "G404: Use of weak random number generator"
      linters:
        - gosec
    - path: pkg/filter/sample/sample\.go
      text: "G404: Use of weak random number generator"
      linters:
        - gosec
    - path: internal/pkg/aws/s3/client\.go
      text: "type assertion on error"
      linters:
        - errorlint
    - path: internal/pkg/aws/s3/client_test\.go
      text: "type assertion on error"
      linters:
        - errorlint
    - path: internal/pkg/aws/s3/error\.go
      text: "type assertion on error"
      linters:
        - errorlint
    - path: pkg/plugins/http/receiver\.go
      text: "SA1029"
      linters:
        - staticcheck
    - path: pkg/plugins/http/receiver\.go
      linters:
        - funlen
    - path: internal/pkg/tablemgr/routing_table_manager\.go
      linters:
        - funlen
